version: 2

jobs:
  build:
    working_directory: ~/project/infra
    machine:
        enabled: true
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install Nix
          command: |
            sudo mkdir -p /nix
            sudo chown circleci /nix
            bash <(curl https://nixos.org/nix/install)
            echo '. /home/circleci/.nix-profile/etc/profile.d/nix.sh' >> $BASH_ENV
            sudo mkdir -p /etc/nix

            # Enable sandbox
            echo "build-use-sandbox = true" | sudo tee -a /etc/nix/nix.conf
            echo "substituters = https://cache.nixos.org https://static-haskell-nix.cachix.org https://deckgo.cachix.org" \
                | sudo tee -a /etc/nix/nix.conf
            echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= static-haskell-nix.cachix.org-1:Q17HawmAwaM1/BfIxaEDKAxwTOyRVhPG5Ji9K3+FvUU= deckgo.cachix.org-1:Kx6Rm054j44GugSRodI2R8T7tAr2u63gKbcCQ9wgaUk=" \
                | sudo tee -a /etc/nix/nix.conf

      - run:
          name: Install cachix
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install

      - run:
          name: Run cachix
          command: |
            cachix push deckgo --watch-store
          background: true

      - run:
          name: Nix build
          command: |
            ls
            pwd
            ./script/test

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: cachix
