name: deckdeckgo-handler
maintainer: Nicolas Mattia <nicolas@nmattia.com>
copyright: (c) 2019 David Dal Busco and Nicolas Mattia
license: AGPL-3

dependencies:
    - aeson
    - bytestring
    - mtl
    - amazonka
    - amazonka-dynamodb
    - base
    - jose
    - lens
    - random
    - servant
    - x509
    - word8
    - pem
    #- servant-auth
    #- servant-auth-server
    - servant-client-core
    - servant-server
    - text
    - unliftio
    - unordered-containers
    - wai
    - wai-cors
    - wai-lambda

ghc-options:
    - -Wall

library:
    source-dirs: src

executables:

    # The AWS Lambda handler
    handler:
        main: app/Handler.hs
        dependencies:
            - deckdeckgo-handler

    server:
        main: app/Server.hs
        dependencies:
            - deckdeckgo-handler
            - warp
            - http-client
            - http-client-tls
            - lens

    test:
        main: app/Test.hs
        dependencies:
            - deckdeckgo-handler
            - http-client
            - servant-client
