name: deckdeckgo-handler
maintainer: Nicolas Mattia <nicolas@nmattia.com>
copyright: (c) 2019 David Dal Busco and Nicolas Mattia
license: AGPL-3

dependencies:
    - aeson
    - mtl
    - amazonka
    - amazonka-dynamodb
    - base
    - lens
    - random
    - servant
    - http-client
    - firebase-login
    - servant-server
    - text
    - unliftio
    - unordered-containers
    - wai
    - wai-cors
    - wai-lambda

ghc-options:
    - -Wall

library:
    source-dirs: src

executables:

    # The AWS Lambda handler
    handler:
        main: app/Handler.hs
        dependencies:
            - deckdeckgo-handler

    # The API
    swagger:
        main: app/Swagger.hs
        dependencies:
            - deckdeckgo-handler
            - servant-swagger
            - servant-swagger-ui

    server:
        main: app/Server.hs
        dependencies:
            - deckdeckgo-handler
            - warp
            - http-client
            - http-client-tls
            - lens

    test:
        main: app/Test.hs
        dependencies:
            - deckdeckgo-handler
            - http-client
            - servant-client
